import React from 'react';
import { Stack, Container, } from '@mui/material';
import Page from '../components/Page';
import CustomizedTitle from '../components/CustomizedComponents/CustomizedTitle';
import CustomizedPaperOutside from '../components/CustomizedComponents/CustomizedPaperOutside';
import { lightBackgroundToTop } from '../components/CustomizedComponents/NeumorphismTheme';

const GeneralConditionsOfSale = () => (
    <Page title="AIOLIA | Conditions générales de vente">
      <Container>
        <Stack direction="row" alignItems="center" justifyContent="space-between" mb={5}>
          <CustomizedTitle sx={{ color: '#787878' }} text="Conditions générales de vente" />
        </Stack>
        <CustomizedPaperOutside sx={{ ...lightBackgroundToTop, background: '#E3EDF7', p: 5, minHeight:'100vh' }}>
          <Stack spacing={2}>
            <div>
              <div className="headerLegalNotice">Conditions générales de vente</div>
              <div>{JSON.parse(localStorage.getItem("user_attr")).hotel_name}</div>
            </div>
            <div>1.Objet</div>
            <div>Les présentes conditions générales définissent les droits et obligations des parties dans le cadre de la réservation à distance de services proposés notre établissement dont les coordonnées sont précisées dans le présent document de confirmation de réservation. Elles régissent toutes les étapes nécessaires à la réservation et au suivi de la réservation entre les parties contractantes. Le client reconnaît avoir pris connaissance et accepté les présentes conditions générales de vente et les conditions de vente du tarif réservé accessibles sur notre plateforme de réservation. Les présentes conditions générales de vente s'appliquent à toutes les réservations conclues par internet, via notre plateforme de réservation.</div>
            <div>
              <div>Réservation</div>
              <div>Le client choisit les services présentés sur notre plateforme de réservation. Il reconnaît avoir pris connaissance de la nature, de la destination et des modalités de réservation des services disponibles sur notre plateforme de réservation et avoir sollicité et obtenu des informations nécessaires et/ou complémentaires pour effectuer sa réservation en parfaite connaissance de cause. Le client est seul responsable de son choix des services et de leur adéquation à ses besoins, de telle sorte que notre responsabilité ne peut être recherchée à cet égard. La réservation est réputée acceptée par le client à l'issue du processus de réservation.</div>
            </div>
            <div>
              <div>Processus de réservation</div>
              <div>Les réservations effectuées par le client se font par l'intermédiaire du bon de réservation dématérialisé accessible en ligne sur notre plateforme de réservation. La réservation est réputée formée dès la réception du bon de réservation. Le client s'engage, préalablement à toute réservation, à compléter les informations demandées sur le bon ou la demande de réservation. Le client atteste de la véracité et de l'exactitude des informations transmises. Après le choix définitif des prestations à réserver, la procédure de réservation comprend notamment la saisie de la carte bancaire en cas de demande de garantie ou de prépaiement, la consultation et l’acceptation des conditions générales de vente et des conditions de vente du tarif réservé avant la validation de la réservation et, enfin, la validation de la réservation par le client.</div>
            </div>
            <div>
              <div>Accusé de réception de la réservation</div>
              <div>Notre plateforme de réservation accuse réception de la réservation du client par l’envoi sans délai d’un courrier électronique. Dans le cas de la réservation en ligne, l'accusé de réception de la réservation par courrier électronique récapitule l'offre de contrat, les services réservés, les prix, les conditions de ventes afférentes au tarif sélectionné, acceptées par le client, la date de réservation effectuée, les informations relatives au service après-vente, ainsi que l’adresse de l’établissement du vendeur auprès duquel le client peut présenter ses réclamations.</div>
            </div>
            <div>
              <div>Annulation ou modification du fait du client</div>
              <div>Il est rappelé au client, conformément à l’article L. 121-21-8 12° du Code de la consommation, qu’il ne dispose pas du droit de rétractation prévu à l’article L. 121-21 du Code de la consommation. Les conditions de vente du tarif réservé précisent les modalités d’annulation et/ou de modification de la réservation. Les réservations avec prépaiement ne pourront faire l’objet d’aucune modification et/ ou annulation. Les sommes versées d’avance que sont les arrhes ne feront l’objet d’aucun remboursement. Dans ce cas, il en est fait mention dans les conditions de vente du tarif. Lorsque les conditions de vente du tarif réservé le permettent, l’annulation de la réservation peut s’effectuer directement auprès de l’établissement, dont les coordonnées téléphoniques sont précisées sur la confirmation de la réservation envoyée par courrier électronique. Toute réservation est nominative et ne peut en aucun cas être cédée à un tiers, que ce soit à titre gratuit ou onéreux.</div>
            </div>
            <div>
              <div>Consommation de la prestation</div>
              <div>En application de la réglementation en vigueur dans certains pays, il pourra être demandé au client, à l’arrivée, de remplir une fiche de police. Pour ce faire, il sera demandé au client de présenter une pièce d’identité afin de vérifier si celui-ci doit compléter ou non la fiche de police. Tout comportement contraire aux bonnes mœurs et à l’ordre public amènera l’établissement à demander au client de quitter l’établissement sans aucune indemnité et ou sans aucun remboursement si un règlement a déjà été effectué. Pour les établissements disposant d’un Règlement Intérieur, le client accepte et s’engage à respecter ledit règlement. En cas de non-respect par le client d’une des dispositions du Règlement Intérieur, l’établissement se trouvera dans l’obligation d’inviter le client à quitter l’établissement sans aucune indemnité et ou sans aucun remboursement si un règlement a déjà été effectué.</div>
            </div>
            <div>
              <div>Responsabilité</div>
              <div>Les photographies présentées sur notre plateforme de réservation ne sont pas contractuelles. Même si tous les meilleurs efforts sont faits pour que les photographies, représentations graphiques et les textes reproduits pour illustrer les établissements présentés donnent un aperçu aussi exact que possible des prestations proposées, des variations peuvent intervenir entre le moment de la réservation et le jour de la consommation du service. L’établissement ne saurait être tenu pour responsable de l'inexécution ou de la mauvaise exécution de la réservation en cas de force majeure, du fait du tiers, du fait du client, notamment l'indisponibilité du réseau internet, impossibilité d’accès au site web, intrusion extérieure, virus informatiques ou en cas prépaiement non autorisé par la banque du porteur. Toute réservation ou paiement qui seraient irréguliers, inopérants, incomplets ou frauduleux pour un motif imputable au client entraînera l’annulation de la commande aux frais du client, sans préjudice de toute action civile ou pénale à l’encontre de ce dernier.</div>
            </div>
            <div>
              <div>Réclamations</div>
              <div>Les réclamations relatives à l’inexécution ou à la mauvaise exécution des prestations réservées doivent, sous peine de forclusion, être portées à notre connaissance par écrit dans les huit jours après la date de départ de l’établissement.</div>
            </div>
            <div>
              <div>Prix</div>
              <div>Les prix afférents à la réservation des services sont indiqués avant et lors de la réservation. Les prix sont confirmés au client en montant TTC, dans la devise commerciale de l’établissement, et ne sont valables que pour la durée indiquée sur la plateforme de réservation. Si le débit à l’établissement s’effectue dans une monnaie autre que celle confirmée sur la réservation, les frais de change sont à la charge du client. Toutes les réservations, quelle que soit leur origine, sont payables dans la monnaie locale de l’établissement, sauf dispositions particulières indiquées sur place. La conversion des devises est fournie à titre d’estimation et de comparaison de prix uniquement. Le coût final du séjour est indiqué dans la devise locale de l’hôtel.Sauf mention contraire sur la plateforme de réservation, les prestations complémentaires ne sont pas incluses dans le prix. Les taxes (taxes locales, taxes de séjour, etc …) le cas échéant, présentées sur la page des tarifs, sont à régler directement sur place auprès de l’établissement. Les prix tiennent compte de la TVA applicable au jour de la commande et tout changement du taux applicable à la TVA sera automatiquement répercuté sur les prix indiqués à la date de facturation.Toute modification ou instauration de nouvelles taxes légales ou réglementaires imposées par les autorités compétentes seront automatiquement répercutées sur les prix indiqués à la date de la facturation.</div>
            </div>
            <div>
              <div>Paiement</div>
              <div>Le client communique ses coordonnées bancaires à titre de garantie de la réservation sauf conditions ou tarifs spéciaux, par carte bancaire de crédit ou privative (Visa, Mastercard, American Express, Diners Club… selon les possibilités offertes par la plateforme de réservation de l'établissement) en indiquant directement, dans la zone prévue à cet effet (saisie sécurisée par cryptage SSL), le numéro de carte, sans espaces entre les chiffres, ainsi que sa date de validité (il est précisé que la carte bancaire utilisée doit être valable au moment de la consommation du service) et le cryptogramme visuel. Il doit se présenter à l’établissement avec la carte bancaire lui ayant permis de garantir la réservation. Le débit du paiement s’effectue à l’établissement lors du séjour, sauf dans le cas de conditions ou tarifs spéciaux où le débit partiel ou total du paiement s’effectue lors de la réservation. Ce prépaiement est qualifié d’arrhes. En cas de no show (réservation non annulée – client non présent) d’une réservation garantie par carte bancaire, l’établissement débitera le client, à titre d’indemnité forfaitaire, du montant indiqué dans ses conditions générales et conditions particulières de vente. L’établissement a choisi <a className="hyperlinkAIOLIA" target="_blank" href="http://aiolia.us/io" rel="noreferrer"><span className="yellowAIOLIA boldAIOLIA">aiolia.us/io</span></a> afin de sécuriser les paiements en ligne par carte bancaire. La validité de la carte de paiement du client est vérifiée par <span className="boldSocieteGenerale">(Société Générale/Aiolia)</span>. Il peut y avoir un refus de la carte de paiement pour plusieurs raisons : carte volée, carte bloquée, plafond atteint, erreur de saisie… En cas de problème, le client devra se rapprocher de sa banque d’une part, de l’établissement d’autre part pour confirmer sa réservation et son mode de paiement. Dans le cas d’un tarif soumis au prépaiement en ligne, la somme versée d’avance, que sont les arrhes, est débitée au moment de la réservation. Certains établissements peuvent générer des factures/notes par voie électronique, le fichier original est certifié et disponible en ligne à l’adresse internet communiquée par l’établissement.</div>
            </div>
            <div>
              <div>Respect de la vie privée</div>
              <div>Le client est informé, sur chacun des formulaires de collecte de données à caractère personnel, du caractère obligatoire ou facultatif des réponses par la présence d’un astérisque. Les informations traitées sont destinées à l’établissements, <a className="hyperlinkAIOLIA" target="_blank" href="http://aiolia.us/io" rel="noreferrer"><span className="yellowAIOLIA">aiolia.us/io</span></a>, à ses entités, à ses partenaires, à ses prestataires (et notamment aux prestataires de paiement en ligne). Le client autorise <a className="hyperlinkAIOLIA" target="_blank" href="http://aiolia.us/io" rel="noreferrer"><span className="yellowAIOLIA">aiolia.us/io</span></a> à communiquer ses données personnelles à des tiers à la condition qu’une telle communication se révèle compatible avec la réalisation des opérations incombant à elloha.com au titre des présentes conditions générales et en lien avec la Charte clients de protection des données personnelles. En particulier lors du paiement en ligne, les coordonnées bancaires du client devront être transmises par le prestataire de paiement <span className="boldSocieteGenerale">Société Générale</span>  à la banque de l’établissement, pour l’exécution du contrat de réservation. Le client est informé que ce transfert de données peut donc s’exécuter dans des pays étrangers ne disposant pas d’une protection des données personnelles adéquate au sens de la loi Informatique et Libertés. Cependant, le client consent à ce transfert nécessaire pour l’exécution de sa réservation. <span className="boldSocieteGenerale">(Société Générale/Aiolia)</span> en leur qualité de professionnel, se sont engagés vis-à-vis de l’établissement à prendre toutes les mesures de sécurité et de respect de la confidentialité des données pour lesdits transferts de données.</div>
            </div>
            <div>
              <div>Convention de preuve</div>
              <div>La saisie des informations bancaires requises, ainsi que l’acceptation des présentes conditions générales et du bon ou de la demande de réservation, constitue une signature électronique qui a, entre les parties, la même valeur qu'une signature manuscrite. Les registres informatisés conservés dans les systèmes informatiques <a className="hyperlinkAIOLIA" target="_blank" href="http://aiolia.us/io" rel="noreferrer"><span className="yellowAIOLIA">aiolia.us/io</span></a> seront conservés dans des conditions raisonnables de sécurité et considérés comme les preuves des communications, des commandes et des paiements intervenus entre les parties. Le client est informé que son adresse IP est enregistrée au moment de la réservation.</div>
            </div>
            <div>
              <div>Force majeure</div>
              <div>La force majeure s’entend de tout évènement extérieur aux parties présentant un caractère à la fois imprévisible et insurmontable qui empêche soit le client, soit l’établissement d’assurer tout ou partie des obligations prévues au contrat. Sont considérés comme cas de force majeure ou cas fortuit ceux habituellement reconnus par la jurisprudence des Cours et Tribunaux français. Chaque partie ne pourra être tenue responsable à l’égard de l’autre partie en cas d’inexécution de ses obligations résultant d’un évènement de force majeure. Il est expressément convenu que la force majeure suspend, pour les parties, l’exécution de leurs obligations réciproques et que chaque partie supporte la charge des frais qui en découlent.</div>
            </div>
            <div>
              <div>Règlement des litiges</div>
              <div>Les présentes Conditions générales de vente sont régies par la loi du pays de l’établissement sans faire obstacle aux dispositions impératives protectrices éventuellement applicables du pays de résidence des consommateurs.</div>
            </div>
            <div>
              <div>Intégralité</div>
              <div>Les présentes Conditions générales de vente, les conditions de vente du tarif réservé par le client, et le bon ou la demande de réservation expriment l'intégralité des obligations des parties. Aucune condition générale ou spécifique communiquée par le client ne pourra s'intégrer aux présentes conditions générales. Les documents formant les engagements contractuels entre les parties sont, par ordre de priorité décroissant, le bon ou la demande de réservation (dont les conditions particulières du tarif réservé) et les présentes conditions générales. En cas de contradiction entre le bon de réservation et les conditions générales, les dispositions figurant au bon de réservation seront les seules applicables pour l’obligation en cause. Les présentes conditions générales de vente par internet peuvent être à tout moment modifiées et/ou complétées par l’établissement. Dans ce cas, la nouvelle version des conditions générales de vente par internet sera mise en ligne par l’établissement. Dès sa mise en ligne sur internet, la nouvelle version des conditions générales de vente par internet s’appliquera automatiquement pour tous les clients.</div>
            </div>
          </Stack>
        </CustomizedPaperOutside>
      </Container>
    </Page>
  );

export default GeneralConditionsOfSale;